---
- name: Install required system packages
  package:
    name:
      - findutils
      - procps
      - passwd
      - hostname
      - git
    state: latest

- name: Clone git rep
  ansible.builtin.git:
    repo: 'https://github.com/CISOfy/lynis.git'
    dest: /tmp/lynis
    clone: true

- name: Run scan and output to file
  shell: ls -la
  args:
    chdir: /tmp/lynis

# - name: Change file ownership, group and permissions
#   ansible.builtin.file:
#     path: /tmp/lynis/
#     owner: root
#     group: root
#     mode: '0777'

# - name: Run scan and output to file
#   shell: ./lynis audit system > "$(hostname -s)_$(date +%d-%m-%Y).report"
#   args:
#     chdir: /tmp/lynis

# - name: Print out report
#   shell: cat /tmp/"$(hostname -s)_$(date +%d-%m-%Y).report"
#   args:
#     chdir: /tmp/lynis

# - name: Remove lynis folder from tmp.
#   file:
#     path: /tmp/lynis
#     state: absent
