---
- name: Install required system packages
  package:
    name:
      - findutils
      - procps
      - passwd
      - hostname
      - git
    state: latest

- name: Clone git rep
  ansible.builtin.git:
    repo: 'https://github.com/CISOfy/lynis.git'
    dest: $HOME/lynis
    clone: true

- name: confirm lynis folder
  find:
    paths: $HOME
    patterns: "lynis*"
    recurse: true
    file_type: directory
  register: found_directories

- debug:
    msg: "{{ [item.path] }} "
  with_items: "{{ found_directories.files }}"

- name: Run scan and output to file
  shell: ./lynis audit system > "$(hostname -s)_$(date +%d-%m-%Y).report"
  args:
    chdir: $HOME/lynis

- name: Print out report
  shell: cat "$(HOME)/$(hostname -s)_$(date +%d-%m-%Y).report"
  args:
    chdir: $HOME/lynis
  register: lynis_report

- debug:
    msg: "{{ [item.path] }} "
  with_items: "{{ lynis_report }}"

- name: Remove lynis folder
  file:
    path: $HOME/lynis
    state: absent
