---
driver:
  name: docker
platforms:
  - name: rockey
    image: "geerlingguy/docker-rockylinux8-ansible:latest"
    tmpfs:
      - /tmp
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: ubuntu
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    tmpfs:
      - /tmp
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
